version: '3'
services:
  backend:
    image: kanban-backend:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    environment:
      - frontend.url=http://localhost:3000
      - gitlabServer.url=https://gitlab.techpm.guru
      - configprops.path=/home/mate/codecool/A38 Kanban project/A38-Kanban-development/src/main/resources/configprops.json
  frontend:
    image: kanban-frontend:latest
    build:
      context: '../A38-Kanban-development-Frontend'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_GITLAB_SERVER=https://gitlab.techpm.guru
      - REACT_APP_GITLAB_APP_ID=458f27c6eb357cf7419231331e3af3e3a9d39782b7edf50ac2cc083e7a7f1a4a
      - REACT_APP_GITLAB_APP_SECRET=f0fbf238c1ef5d0be56bf1118c430b15daff2b85d790d4bbfd76b8ccbb5bac33
      - REACT_APP_APPLICATION=http://localhost:3000
    stdin_open: true