version: '3'
services:
  backend:
    image: kanban-backend:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
    - '8080:8080'
    environment:
      - frontend.url=http://localhost:3000
  frontend:
    image: kanban-frontend:latest
    build:
      context: '../A38-Kanban-development-Frontend/kanban'
      dockerfile: 'Dockerfile'
    ports:
    - '3000:3000'
    environment:
      - REACT_APP_SERVER=http://localhost:8080
    stdin_open: true