version: '3'
services:
  backend:
    image: kanban-backend:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    environment:
      - frontend.url=http://localhost:3000
      - gitlabServer.url=https://gitlab.techpm.guru
      - app.secret=f0fbf238c1ef5d0be56bf1118c430b15daff2b85d790d4bbfd76b8ccbb5bac33
      - configprops.path=/config/configprops.json
    volumes:
      - ./data:/config
  frontend:
    image: kanban-frontend:latest
    build:
      context: '../A38-Kanban-development-Frontend'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    stdin_open: true